export enum PermissionType {
  USERS_CREATE = "users:create",
  USERS_READ = "users:read",
  USERS_EDIT = "users:edit",
  USERS_DELETE = "users:delete",
  EVENTS_CREATE = "events:create",
  EVENTS_READ = "events:read",
  EVENTS_EDIT = "events:edit",
  EVENTS_DELETE = "events:delete",
  ROLES_CREATE = "roles:create",
  ROLES_READ = "roles:read",
  ROLES_EDIT = "roles:edit",
  ROLES_DELETE = "roles:delete",
  PERMISSIONS_CREATE = "permissions:create",
  PERMISSIONS_READ = "permissions:read",
  PERMISSIONS_EDIT = "permissions:edit",
  PERMISSIONS_DELETE = "permissions:delete",
}
